"""Add vendor and description to server

Revision ID: 737b8ca2f30f
Revises: 
Create Date: 2024-02-28 01:16:09.690813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737b8ca2f30f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('vendor')

    # ### end Alembic commands ###
